/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/AuthLogin': RouteRecordInfo<'/AuthLogin', '/AuthLogin', Record<never, never>, Record<never, never>>,
    '/AuthRegister': RouteRecordInfo<'/AuthRegister', '/AuthRegister', Record<never, never>, Record<never, never>>,
    '/Cards': RouteRecordInfo<'/Cards', '/Cards', Record<never, never>, Record<never, never>>,
    '/DeckDetails': RouteRecordInfo<'/DeckDetails', '/DeckDetails', Record<never, never>, Record<never, never>>,
    '/DecksOverview': RouteRecordInfo<'/DecksOverview', '/DecksOverview', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/ImportsOverview': RouteRecordInfo<'/ImportsOverview', '/ImportsOverview', Record<never, never>, Record<never, never>>,
    '/Main': RouteRecordInfo<'/Main', '/Main', Record<never, never>, Record<never, never>>,
  }
}
