name: Build and Deploy

on: [push, workflow_dispatch]

jobs:
  application_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies and run API tests
        run: |
          cd api
          npm install
          npm test

  build_and_push_api:
    needs: application_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build API Docker Image
        run: |
          docker build -t magic-the-gathering-api ./api

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push API Docker Image
        run: |
          docker tag magic-the-gathering-api "${{ secrets.DOCKERHUB_USERNAME }}/magic-the-gathering-api"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/magic-the-gathering-api"